import { getSession, session } from 'next-auth/client';
import Head from 'next/head'
import Header from '../components/Header';
import Login from '../components/Login';

export default function Home({session}) {

  if(!session)    return <Login/>;


  return (
    <div>
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header/>

      <main>

        {/* SideBar */}
      

        {/* Feed */}
        {/* Widget */}

      </main>

      
    </div>
  )
}

export async function getServerSideProps(context){

    //get the user
    const session=await getSession(context);

    return {
      props:{
        session
      }
    }

}
